# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CheckSsh < Formula
  desc "Audits sshd for weak or insecure algorithms across local, file-based, and remote scans, and generates a drop-in hardening config."
  homepage "https://github.com/krisiasty/check-ssh"
  version "1.0.1"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/krisiasty/check-ssh/releases/download/v1.0.1/check-ssh_1.0.1_darwin_amd64.tar.gz"
    sha256 "eb08fecb83d309d6203192c1802d1ed30f0da8ad534d8a2d33f53a819bf2d31b"

    define_method(:install) do
      bin.install "check-ssh"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/krisiasty/check-ssh/releases/download/v1.0.1/check-ssh_1.0.1_darwin_arm64.tar.gz"
    sha256 "561d977cb3c2bd9bb960182858fffedc42dee672a1e6fa27032d7d59e5efd566"

    define_method(:install) do
      bin.install "check-ssh"
    end
  end
end
