# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NetdevSshMcp < Formula
  desc "MCP server for SSH-based network device operations (Arista EOS, Cisco NX-OS, IOS/IOS-XE)"
  homepage "https://github.com/krisiasty/netdev-ssh-mcp"
  version "1.6.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/krisiasty/netdev-ssh-mcp/releases/download/v1.6.0/netdev-ssh-mcp_1.6.0_darwin_amd64.tar.gz"
    sha256 "44432aba0e6c89f2b9ec9a7507583ec3753dc8fd40b889f25e258dcef5fcb300"

    define_method(:install) do
      bin.install "netdev-ssh-mcp"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/krisiasty/netdev-ssh-mcp/releases/download/v1.6.0/netdev-ssh-mcp_1.6.0_darwin_arm64.tar.gz"
    sha256 "703cbaf11bc105d78cd0dc4568cdda817cb76a9317f77edfa04056dcb6512bb1"

    define_method(:install) do
      bin.install "netdev-ssh-mcp"
    end
  end
end
