# This file was generated by GoReleaser. DO NOT EDIT.
cask "aptmir" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "bb84f898e431a0817d249d6e589648bd138e12a2bf82bba659bf4fbaacdfbe74"
      url "https://github.com/krisiasty/aptmir/releases/download/v#{version}/aptmir_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed1e923d0e86d7a176cb8244d635d9cdfdd6585b84c2c1db13d160bcf6cd56dc"
      url "https://github.com/krisiasty/aptmir/releases/download/v#{version}/aptmir_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "aptmir"
  desc "Ranks Ubuntu archive mirrors by measured freshness and throughput"
  homepage "https://github.com/krisiasty/aptmir"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aptmir"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
