# This file was generated by GoReleaser. DO NOT EDIT.
cask "aptmir" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f9435bdc8880c459ebcb8254a919b68421f67147419d82a760fbf0d06082bb88"
      url "https://github.com/krisiasty/aptmir/releases/download/v#{version}/aptmir_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f27b326bf15edf90570d69359db15477272926c1c797f0084c6136dabf0d6bbe"
      url "https://github.com/krisiasty/aptmir/releases/download/v#{version}/aptmir_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "aptmir"
  desc "Ranks Ubuntu archive mirrors by measured freshness and throughput"
  homepage "https://github.com/krisiasty/aptmir"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aptmir"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
