# This file was generated by GoReleaser. DO NOT EDIT.
cask "aptmir" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "ac58a02eb5c32305ed9db3adc99ebe399be6d52601649407a8917d2b40b88c3b"
      url "https://github.com/krisiasty/aptmir/releases/download/v#{version}/aptmir_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7fdbd017caa583573a6065a787ce84aee4264cdcdb65064cd78118a254107ec4"
      url "https://github.com/krisiasty/aptmir/releases/download/v#{version}/aptmir_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "aptmir"
  desc "Ranks Ubuntu archive mirrors by measured freshness and throughput"
  homepage "https://github.com/krisiasty/aptmir"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aptmir"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
