# This file was generated by GoReleaser. DO NOT EDIT.
cask "certfinder" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "c959c6c8bae641831233f02f5439077eb946dcfd72ee2ffce86f867e2af92286"
      url "https://github.com/krisiasty/certfinder/releases/download/v#{version}/certfinder_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ac0028b2740acb5c1bbcb8d286048c62930e1d5e41ba48a288db69400a8dc2b1"
      url "https://github.com/krisiasty/certfinder/releases/download/v#{version}/certfinder_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "certfinder"
  desc "X.509 certificate discovery and reporting tool"
  homepage "https://github.com/krisiasty/certfinder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certfinder"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
