# This file was generated by GoReleaser. DO NOT EDIT.
cask "certfinder" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "7ed64b13bf8a669b44a3f3744b8d8dba394affd855e2b5db3368b12436ff319b"
      url "https://github.com/krisiasty/certfinder/releases/download/v#{version}/certfinder_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "93b282bc988eda7e396765717743738363188cf8d2577f9fb58667f868e0ee25"
      url "https://github.com/krisiasty/certfinder/releases/download/v#{version}/certfinder_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "certfinder"
  desc "X.509 certificate discovery and reporting tool"
  homepage "https://github.com/krisiasty/certfinder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certfinder"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
