# This file was generated by GoReleaser. DO NOT EDIT.
cask "certfinder" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "39da2d905893d6b75a92c80be334f244e3167cd156ceda56129e88476042352e"
      url "https://github.com/krisiasty/certfinder/releases/download/v#{version}/certfinder_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b61e9c94063858823b850a445970eaf934b3e1448c5c2e324b66fc27730f26b"
      url "https://github.com/krisiasty/certfinder/releases/download/v#{version}/certfinder_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "certfinder"
  desc "X.509 certificate discovery and reporting tool"
  homepage "https://github.com/krisiasty/certfinder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certfinder"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
