# This file was generated by GoReleaser. DO NOT EDIT.
cask "check-ssh" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "cd7dfbacad45dc39559a0098115350e8bdf9f8df068a79fff60012534695a0ce"
      url "https://github.com/krisiasty/check-ssh/releases/download/v#{version}/check-ssh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0165c6725d33388f094beadc2289edb494c1b1783b1964d83b4c0052a1d14a7b"
      url "https://github.com/krisiasty/check-ssh/releases/download/v#{version}/check-ssh_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "check-ssh"
  desc "Audits sshd for weak or insecure algorithms across local, file-based, and remote scans, and generates a drop-in hardening config."
  homepage "https://github.com/krisiasty/check-ssh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "check-ssh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
