# This file was generated by GoReleaser. DO NOT EDIT.
cask "check-ssh" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "9b7284dd5ea68a4e1da2e9ec338e68e76fd74acad3feb0992c766a4866662931"
      url "https://github.com/krisiasty/check-ssh/releases/download/v#{version}/check-ssh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b1b7d98ce5a474a4770e8acf865eeb8194dfef6664adcf0d5542d69d1ef3a2d"
      url "https://github.com/krisiasty/check-ssh/releases/download/v#{version}/check-ssh_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "check-ssh"
  desc "Audits sshd for weak or insecure algorithms across local, file-based, and remote scans, and generates a drop-in hardening config."
  homepage "https://github.com/krisiasty/check-ssh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "check-ssh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
