# This file was generated by GoReleaser. DO NOT EDIT.
cask "check-ssh" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "f916e9c869fca907dbb45da6a17a1d38242018252701838ba07e56722ad2dcb8"
      url "https://github.com/krisiasty/check-ssh/releases/download/v#{version}/check-ssh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "48b6c14730366a67cf001a02a0b3174b6eac3bbf6742f2a5574813f62f126df6"
      url "https://github.com/krisiasty/check-ssh/releases/download/v#{version}/check-ssh_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "check-ssh"
  desc "Audits sshd for weak or insecure algorithms across local, file-based, and remote scans, and generates a drop-in hardening config."
  homepage "https://github.com/krisiasty/check-ssh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "check-ssh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
