# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghget" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "63d0ad907fe46b3663d877210b6582de03de9dba22fbd52325e209c22b81f997"
      url "https://github.com/krisiasty/ghget/releases/download/v#{version}/ghget_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9717171b749428eee3729732ff5cc911cee0259bd2dedbcf7ea60aa893a7fae"
      url "https://github.com/krisiasty/ghget/releases/download/v#{version}/ghget_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "ghget"
  desc "Smart GitHub release downloader for public repositories"
  homepage "https://github.com/krisiasty/ghget"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghget"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
