# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghget" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "bca6ff516a9c00788e364299da04a60a86a0328c2b9a0a9ea72808bae3b212c1"
      url "https://github.com/krisiasty/ghget/releases/download/v#{version}/ghget_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "94a62140f202790dc11c5d77a392404021d895e1bec320e9dcc83b92fb4eb13e"
      url "https://github.com/krisiasty/ghget/releases/download/v#{version}/ghget_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "ghget"
  desc "Smart GitHub release downloader for public repositories"
  homepage "https://github.com/krisiasty/ghget"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghget"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
