# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghget" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "69ef80afe7bfa8e5710c4c96ca3c79e8287bda70506f6ba720303573bfe9876c"
      url "https://github.com/krisiasty/ghget/releases/download/v#{version}/ghget_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b7c5fb2a5a7353766e4aed30be1a497f542c78a62a7daf83eb865378fffbd486"
      url "https://github.com/krisiasty/ghget/releases/download/v#{version}/ghget_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "ghget"
  desc "Smart GitHub release downloader for public repositories"
  homepage "https://github.com/krisiasty/ghget"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghget"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
