# This file was generated by GoReleaser. DO NOT EDIT.
cask "netdev-ssh-mcp" do
  version "1.6.2"

  on_macos do
    on_intel do
      sha256 "0e5cf2ac154ce583ed255392be7932b246bb2d0690fb423e1c87b752588ffc05"
      url "https://github.com/krisiasty/netdev-ssh-mcp/releases/download/v#{version}/netdev-ssh-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "53c2ff818b32737e1e3f0e2d7056f192dc5acb84f86f587d1454449bf1a41369"
      url "https://github.com/krisiasty/netdev-ssh-mcp/releases/download/v#{version}/netdev-ssh-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "netdev-ssh-mcp"
  desc "MCP server for SSH-based network device operations (Arista EOS, Cisco NX-OS, IOS/IOS-XE)"
  homepage "https://github.com/krisiasty/netdev-ssh-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "netdev-ssh-mcp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
