# This file was generated by GoReleaser. DO NOT EDIT.
cask "netdev-ssh-mcp" do
  version "1.6.6"

  on_macos do
    on_arm do
      sha256 "4cda4376774c1b7f204731badd1e4fe930205c47680634153d790b8fcaa906e6"
      url "https://github.com/krisiasty/netdev-ssh-mcp/releases/download/v#{version}/netdev-ssh-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa8f39a903d47e06fe498ce92ff9b31be51db855b1eacdcd03bf28b440660924"
      url "https://github.com/krisiasty/netdev-ssh-mcp/releases/download/v#{version}/netdev-ssh-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "netdev-ssh-mcp"
  desc "MCP server for SSH-based network device operations (Arista EOS, Cisco NX-OS, IOS/IOS-XE)"
  homepage "https://github.com/krisiasty/netdev-ssh-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "netdev-ssh-mcp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
