# This file was generated by GoReleaser. DO NOT EDIT.
cask "netdev-ssh-mcp" do
  version "1.6.3"

  on_macos do
    on_intel do
      sha256 "a03ec62cb48b72802fb9a7a6f3626481071dcb4ef4f3089424759fa2b1f98196"
      url "https://github.com/krisiasty/netdev-ssh-mcp/releases/download/v#{version}/netdev-ssh-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c01aa9142fad4edd78d102df4f58c0ec64dc1d43d5417ab148fec2c5ee32779e"
      url "https://github.com/krisiasty/netdev-ssh-mcp/releases/download/v#{version}/netdev-ssh-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "netdev-ssh-mcp"
  desc "MCP server for SSH-based network device operations (Arista EOS, Cisco NX-OS, IOS/IOS-XE)"
  homepage "https://github.com/krisiasty/netdev-ssh-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "netdev-ssh-mcp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
