# This file was generated by GoReleaser. DO NOT EDIT.
cask "olb" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "00141652baefc204aa3321428216852d16cfd9a7554a56d2051aba7536c3c6e5"
      url "https://github.com/krisiasty/olb/releases/download/v#{version}/olb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "73fee15ff3b2b5af5a5e88ff6f89b4ad7fc173df711f8e522e2e11d52b51e2ff"
      url "https://github.com/krisiasty/olb/releases/download/v#{version}/olb_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "olb"
  desc "Interactive terminal UI for inspecting OpenStack Octavia load balancers (Amphora and OVN providers)."
  homepage "https://github.com/krisiasty/olb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "olb"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
