# This file was generated by GoReleaser. DO NOT EDIT.
cask "olb" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "d08d70f813d337a9995eba004c872e1ac49ea4ab2e0099734ee6aa25dc85931e"
      url "https://github.com/krisiasty/olb/releases/download/v#{version}/olb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a6a2442fb49dc1a28914bf07e5dc5037818f3c642f5945c61e89776cdda5d91"
      url "https://github.com/krisiasty/olb/releases/download/v#{version}/olb_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "olb"
  desc "Interactive terminal UI for inspecting OpenStack Octavia load balancers (Amphora and OVN providers)."
  homepage "https://github.com/krisiasty/olb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "olb"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
