# This file was generated by GoReleaser. DO NOT EDIT.
cask "olb" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "e77681c056598412b5037f43491b942803c97b702b3e5b9a2f79a4e2f319aa2a"
      url "https://github.com/krisiasty/olb/releases/download/v#{version}/olb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fefbbff4e6b3baf0ed3753a6a1031e501b50cd290ce7072d4d0f406d6942dc1b"
      url "https://github.com/krisiasty/olb/releases/download/v#{version}/olb_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "olb"
  desc "Interactive terminal UI for inspecting OpenStack Octavia load balancers (Amphora and OVN providers)."
  homepage "https://github.com/krisiasty/olb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "olb"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
