# This file was generated by GoReleaser. DO NOT EDIT.
cask "promtop" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "eb48b801f7d79839411d1dcceadfc1ed3055f10f4729687b53d6aa7a3afb2c59"
      url "https://github.com/krisiasty/promtop/releases/download/v#{version}/promtop_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e8d6b081d6d42d65a5d29a81eafebb07e82e5dc49ea1e17bbc1ac1074366c81"
      url "https://github.com/krisiasty/promtop/releases/download/v#{version}/promtop_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "promtop"
  desc "Terminal UI for exploring a single Prometheus metrics endpoint"
  homepage "https://github.com/krisiasty/promtop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promtop"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
