# This file was generated by GoReleaser. DO NOT EDIT.
cask "promtop" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "3ec5d5b3583bab57067c48fd5f3307546f91b078933bc6e80989dfe6d05d18b9"
      url "https://github.com/krisiasty/promtop/releases/download/v#{version}/promtop_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e95aee9aa2804a78628eabfc8e5365f283221b94940b46c198b5e62a91e712cd"
      url "https://github.com/krisiasty/promtop/releases/download/v#{version}/promtop_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "promtop"
  desc "Terminal UI for exploring a single Prometheus metrics endpoint"
  homepage "https://github.com/krisiasty/promtop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promtop"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
