# This file was generated by GoReleaser. DO NOT EDIT.
cask "promtop" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "b85a2dbca1a439862f6378073f32878e0f124f547e9f39dfff182fca9404fb04"
      url "https://github.com/krisiasty/promtop/releases/download/v#{version}/promtop_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "943e4d5aad9e2cd02fca931a7315299f46916d8d0bef285e25d108391bab95e7"
      url "https://github.com/krisiasty/promtop/releases/download/v#{version}/promtop_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "promtop"
  desc "Terminal UI for exploring a single Prometheus metrics endpoint"
  homepage "https://github.com/krisiasty/promtop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promtop"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
