# This file was generated by GoReleaser. DO NOT EDIT.
cask "rgwt" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "8f1732218fdd75a4b92d8cc777508258e36cd254307df77405b5b5903a4cc796"
      url "https://github.com/krisiasty/rgwt/releases/download/v#{version}/rgwt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e117e715f7e0a51f74386fcd39a15b88461090fbc37d04fd5fa9faefb57c3df4"
      url "https://github.com/krisiasty/rgwt/releases/download/v#{version}/rgwt_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "rgwt"
  desc "Read-only terminal browser for Ceph RADOS Gateway administration."
  homepage "https://github.com/krisiasty/rgwt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rgwt"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
