# This file was generated by GoReleaser. DO NOT EDIT.
cask "rgwt" do
  version "1.3.1"

  on_macos do
    on_arm do
      sha256 "ce22813a8b7046488f0e74d7c5480e74706628afd2ded62c54a57ae0f504dc1b"
      url "https://github.com/krisiasty/rgwt/releases/download/v#{version}/rgwt_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "15e5a586b959a64d31533fb2fcbe8414a9a821539a0bf54e31a5bfd6b0cfe062"
      url "https://github.com/krisiasty/rgwt/releases/download/v#{version}/rgwt_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "rgwt"
  desc "Read-only terminal browser for Ceph RADOS Gateway administration."
  homepage "https://github.com/krisiasty/rgwt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rgwt"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required
end
