# This file was generated by GoReleaser. DO NOT EDIT.
cask "rgwt" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "fcc515d8417516158906bc9bf6884064af5d412e64db607439d2408407e8d54b"
      url "https://github.com/krisiasty/rgwt/releases/download/v#{version}/rgwt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "255c40b31726b6c0fc746902d1d4e9b1bb0f1d6d7406ca5eb71c5cb92b453f40"
      url "https://github.com/krisiasty/rgwt/releases/download/v#{version}/rgwt_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "rgwt"
  desc "Read-only terminal browser for Ceph RADOS Gateway administration."
  homepage "https://github.com/krisiasty/rgwt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rgwt"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
