# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-agent-proxy" do
  version "0.99.2"

  on_macos do
    on_intel do
      sha256 "13e63712857f7149a2290e4e6abe0748bebb8ad86592a9b1c98c83a2071eff47"
      url "https://github.com/krisiasty/ssh-agent-proxy/releases/download/v#{version}/ssh-agent-proxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ce59abbd3e939b21632d6d70d5ada6dfc860222d24faf32c91cf38e4f88e21f"
      url "https://github.com/krisiasty/ssh-agent-proxy/releases/download/v#{version}/ssh-agent-proxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ssh-agent-proxy"
  desc "Filtering proxy for ssh-agent: expose per-group filtered views of your keys"
  homepage "https://github.com/krisiasty/ssh-agent-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-agent-proxy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

  caveats <<~EOS
    Configure ssh-agent-proxy, then install the LaunchAgent with:
      ssh-agent-proxy -install
    Config lives at ~/Library/Application Support/ssh-agent-proxy/config.yaml
  EOS
end
