# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-agent-proxy" do
  version "0.99.1"

  on_macos do
    on_intel do
      sha256 "75db57dd4ac3f2e0db8e3d020f5229795e8965364c449263f45f752cbd2670e2"
      url "https://github.com/krisiasty/ssh-agent-proxy/releases/download/v#{version}/ssh-agent-proxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3fda13273a6e7f9cc42d7d5cc7c4ff05b9b28615d202166a1f7d2199e8835cb2"
      url "https://github.com/krisiasty/ssh-agent-proxy/releases/download/v#{version}/ssh-agent-proxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ssh-agent-proxy"
  desc "Filtering proxy for ssh-agent: expose per-group filtered views of your keys"
  homepage "https://github.com/krisiasty/ssh-agent-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-agent-proxy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

  caveats <<~EOS
    Configure ssh-agent-proxy, then install the LaunchAgent with:
      ssh-agent-proxy -install
    Config lives at ~/Library/Application Support/ssh-agent-proxy/config.yaml
  EOS
end
