# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-agent-proxy" do
  version "0.99.0"

  on_macos do
    on_intel do
      sha256 "7bef75562570b52f5b32c4560ccc0d5f72fd3e71538e2155ab776c05ef2c8dc0"
      url "https://github.com/krisiasty/ssh-agent-proxy/releases/download/v#{version}/ssh-agent-proxy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a54c30c3ede242cbe386e2bfb705d3985e9078f84e30abfb0a5b0e221c7e0cca"
      url "https://github.com/krisiasty/ssh-agent-proxy/releases/download/v#{version}/ssh-agent-proxy_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "ssh-agent-proxy"
  desc "Filtering proxy for ssh-agent: expose per-group filtered views of your keys"
  homepage "https://github.com/krisiasty/ssh-agent-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-agent-proxy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

  caveats <<~EOS
    Configure ssh-agent-proxy, then install the LaunchAgent with:
      ssh-agent-proxy -install
    Config lives at ~/Library/Application Support/ssh-agent-proxy/config.yaml
  EOS
end
