# This file was generated by GoReleaser. DO NOT EDIT.
cask "vcheck" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "3bbfdbdaad5cd5f4c5aa7180a849e36c0bed3a9c0226a0f82e9ae1cd0625a0ff"
      url "https://github.com/krisiasty/vcheck/releases/download/v#{version}/vcheck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d1745be561146a19a22aada4ffbd2b3a707f14f1887e01161449a0307dc1b55c"
      url "https://github.com/krisiasty/vcheck/releases/download/v#{version}/vcheck_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "vcheck"
  desc "Audits remote Linux hosts over SSH for Copy Fail and Dirty Frag kernel-module vulnerabilities."
  homepage "https://github.com/krisiasty/vcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vcheck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
