# This file was generated by GoReleaser. DO NOT EDIT.
cask "vcheck" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "277dab7f0e4c92835ecb937f3f976fd658b8ffa16dd6a7beb7355eeefbe5b230"
      url "https://github.com/krisiasty/vcheck/releases/download/v#{version}/vcheck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1580dbf4e4419fd18e9a5234791d7100776b192c7bb60dd1226647e2bfadfb95"
      url "https://github.com/krisiasty/vcheck/releases/download/v#{version}/vcheck_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "vcheck"
  desc "Audits remote Linux hosts over SSH for Copy Fail and Dirty Frag kernel-module vulnerabilities."
  homepage "https://github.com/krisiasty/vcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vcheck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
