# This file was generated by GoReleaser. DO NOT EDIT.
cask "vcheck" do
  version "1.6.1"

  on_macos do
    on_intel do
      sha256 "46bce99b1f578960ad0b2f334967716801c9d14bed06509a1985fa93ee545a4f"
      url "https://github.com/krisiasty/vcheck/releases/download/v#{version}/vcheck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "862dcb12cb3b87c35fcafe5a0fc9d94db45f8b1189ed35e0e335a5d69a7f193d"
      url "https://github.com/krisiasty/vcheck/releases/download/v#{version}/vcheck_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "vcheck"
  desc "Audits remote Linux hosts over SSH for Copy Fail and Dirty Frag kernel-module vulnerabilities."
  homepage "https://github.com/krisiasty/vcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vcheck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  # No zap stanza required

end
